In [1]:
# Creating an Array 
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [2]:
a = np.array({'Name':'Harsh','age':25})
print(a)

{'Name': 'Harsh', 'age': 25}


In [3]:
#addition 
a = np.array([1,2,3,4,5])
b = np.array([2,3,4,5,6])
add = a + b
print(add)

[ 3  5  7  9 11]


In [4]:
import time 
size = 100000
x = np.array(size)
y = np.array(size)
start = np.array(size)
r = x + y
print(r,"NUmpy array time:",time.time() - start)

200000 NUmpy array time: 1763378075.2303863


In [5]:
# Memory Usage Comparison
s = np.array([1,2,3,4,5])
print("NumPy array memory:",s.nbytes)

NumPy array memory: 40


In [6]:
#create 2D array 
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
#Creates array of zeros
np.zeros(5)
# Creates array of ones
np.ones(3)
#Creates array with range - np.arange(start, stop, step)
np.arange(1,10,2)
# Creates evenly spaced numbers - np.linspace(start, stop, num)
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [ ]:
# Creating Arrays with Random Values
''' 
np.random.rand() → random float values.
np.random.randint() → random integer values

'''
r = np.random.rand(3) # Random values between 0 and 1
print(r)
s = np.random.randint(1,10,5) # 5 random integers from 1 to 9
print(s)

[0.82521001 0.38161839 0.81191987]
[7 9 1 6 6]


In [20]:
# Checking Array Dimensions
''' 
ndim → tells how many dimensions (1D, 2D, etc.)
shape → gives structure of array.
size → total number of elements in the array.
dtype → data type of elements
itemsize → memory (bytes) used by each element
'''
w = np.array([[[1,2,3],[4,5,6]],[[8,9,10],[11,12,13]]])
print(w.ndim)
print(w.shape)
print(w.size)
print(w.dtype)
print(w.itemsize)

3
(2, 2, 3)
12
int64
8


In [ ]:
#Reshape -Reshaping means changing the shape of an existing array without changing the data.
# The total number of elements must remain the same.
#Returns a new array with new shape
arr = np.array([1, 2, 3, 4, 5, 6])
#1D to 2D Reshape
reshaped = arr.reshape(2, 3)
# print(reshaped)
# 1D to 3D Reshape
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reshaped = arr1.reshape(2, 2, 2)
# print(reshaped)
#Errors
# ar = np.array([1, 2, 3, 4, 5])
# ar.reshape(2, 3)
# Fix: Ensure total elements match: 2 × 3 = 6 elements required.

#Using -1 in Reshape
a = np.array([1, 2, 3, 4, 5, 6])
reshaped = a.reshape(3, -1)
print(reshaped)
''' Explanation:
NumPy automatically calculates the missing dimension when you use 1 .
Here, 6 elements / 3 rows = 2 columns.'''

#Flattening an Array
arr = np.array([[1, 2, 3], [4, 5, 6]])
flat = arr.reshape(-1)
print(flat)
''' reshape(-1) converts any multi-dimensional array into a 1D array. Also known as flattening the array.'''

# resize() Changes the shape of the same array
# Reshape ≠ Resize — reshape returns new array, resize changes original.

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [ ]:
'''
- Indexing means accessing specific elements from a NumPy array.
- Slicing means extracting a range or part of the array.
- Indexing starts from 0 (just like in Python lists).
- Works for 1D, 2D, and multi-dimensional arrays.
- Helps in data manipulation and selection. '''

# Indexing in 1D Array
arr = np.array([10, 20, 30, 40, 50])
print(arr[0]) # First element
print(arr[3]) # Fourth element
#Negative Indexing - Negative indexes count from the end. - 1 → last element, 2 → second last
print(arr[-1]) # Last element
print(arr[-3]) # Third element from the end

# Indexing in 2D Array
arr2d = np.array([[10, 20, 30],
[40, 50, 60]])
print(arr2d[0, 1]) # Row 0, Column 1 - 20
print(arr2d[0, 0]) # Row 0, Column 0 - 10
print(arr2d[1, 2]) # Row 1, Column 2 - 60

10
40
50
30


In [ ]:
# Slicing in 1D Array
''' 
Syntax: arr[start:end]
start is included, end is excluded.
'''
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[1:4]) # From index 1 to 3
print(arr[:3]) # From start to index 2
print(arr[3:]) # From index 3 to end

# Slicing in 2D Array
''' 
Syntax: arr[row_start:row_end, col_start:col_end]
Selects a sub-matrix from the array.
'''
arr2d = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
print(arr2d.ndim)
print(arr2d[0:2, 1:3]) # Rows 0–1, Columns 1–2

# Step Value in Slicing
''' 
Syntax: arr[start:end:step]
Step defines how many elements to skip.
'''
arr = np.array([10, 20, 30, 40, 50, 60, 70])
print(arr[::2]) # Every 2nd element
print(arr[::-1]) # reverse 
print(arr[1:4]) # Every 2nd element
print(arr[1:6:2]) # From 1 to 5, step of 2

# Modifying Values using Indexing
''' 
You can update elements directly using indexes.
NumPy arrays are mutable (can be changed).
'''
arr = np.array([1, 2, 3, 4, 5])
arr[2] = 99
print(arr)

[20 30 40]
[10 20 30]
[40 50 60]
2
[[20 30]
 [50 60]]
[10 30 50 70]
[70 60 50 40 30 20 10]
[20 30 40]
[20 40 60]
[ 1  2 99  4  5]


In [ ]:
''' 
Vectorization means performing operations on entire arrays instead of using
loops.
It allows you to write clean, faster, and more efficient code.
NumPy automatically applies operations element-wise on arrays.
'''
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])
addition = arr1 + arr2
Subtraction = arr2 - arr1 
Multiplication =  arr1 * arr2
Division  = arr2 / arr1 
Power =  arr1 ** 2 
print(addition)
print(Subtraction)
print(Multiplication)
print(Division)
print(Power)

# Vectorization with Functions
arr = np.array([1, 2, 3, 4, 5])
print(np.sqrt(arr)) # Square root
print(np.square(arr)) # Square
print(np.exp(arr)) # Exponential
print(np.log(arr)) # Logarithm
''' 
These functions work on entire arrays at once.
No need for manual loops — fully vectorized.
'''

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.         2.23606798]
[ 1  4  9 16 25]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
# Joining 1D Arrays using concatenate()
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.concatenate((arr1, arr2))
print(result)
''' 
concatenate() joins arrays along an existing axis.
For 1D arrays, it joins them end to end.
'''
# Joining 2D Arrays using concatenate()
'''axis=0 → join vertically (rows).
axis=1 → join horizontally (columns).'''
arr1 = np.array([[1, 2],[3, 4]])
arr2 = np.array([[5, 6],[7, 8]])
result1 = np.concatenate((arr1, arr2), axis=0) # Row-wise
result2 = np.concatenate((arr1, arr2), axis=1) # Column-wise
print("Row-wise:\n", result1)
print("Column-wise:\n", result2)

[1 2 3 4 5 6]
Row-wise:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Column-wise:
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# Joining Arrays using hstack() and vstack()
''' hstack() joins arrays side by side (columns).
vstack() joins arrays top to bottom (rows).'''
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
h = np.hstack((arr1, arr2))
v = np.vstack((arr1, arr2))
print("Horizontal Stack:", h)
print("Vertical Stack:\n", v)

Horizontal Stack: [1 2 3 4 5 6]
Vertical Stack:
 [[1 2 3]
 [4 5 6]]


In [57]:
# Using np.stack() for New Dimensions
''' stack() joins arrays along a new axis.
Here, a new column dimension is created.'''
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked = np.stack((arr1, arr2), axis=1)
print(stacked)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Splitting 1D Array using split()
''' np.split(array, 3) splits array into 3 equal parts.
The number of elements must be divisible by parts.'''
arr = np.array([10, 20, 30, 40, 50, 60])
result = np.split(arr, 3)
print(result)

In [ ]:
# Unequal Splitting using array_split()
'''array_split() allows unequal splitting.
Useful when total elements can’t be divided equally.'''
arr = np.array([1, 2, 3, 4, 5])
result = np.array_split(arr, 3)
print(result)

[array([1, 2]), array([3, 4]), array([5])]


In [ ]:
# Splitting 2D Arrays
'''hsplit() → splits horizontally (columns).
vsplit() → splits vertically (rows).'''
arr2d = np.array([[10, 20, 30, 40],
[50, 60, 70, 80]])
print(np.hsplit(arr2d, 2)) # Split columns
print(np.vsplit(arr2d, 2)) # Split rows

[array([[10, 20],
       [50, 60]]), array([[30, 40],
       [70, 80]])]
[array([[10, 20, 30, 40]]), array([[50, 60, 70, 80]])]


In [ ]:
'''Broadcasting allows NumPy to perform operations on arrays of different
shapes and sizes.
Normally, arrays must have the same shape to perform element-wise
operations.
Broadcasting automatically expands smaller arrays to match larger ones.
Makes operations faster, simpler, and memory-efficient.
Used heavily in machine learning and numerical computation.'''
# NumPy cannot add arrays with incompatible shapes.
# a.shape = (3,) and b.shape = (2,) → ❌ Not compatible.


In [ ]:
'''
# Broadcasting Works When Shapes Match Rules
Broadcasting works when:

Broadcasting in NumPy 1

1. The arrays have same number of dimensions, or
2. The smaller array can expand along dimension = 1, or
3. The dimensions are compatible from right to left.
'''
# Scalar and Array
'''Scalar 10 is broadcasted to each element of the array.
Equivalent to [1,2,3,4] + [10,10,10,10] .'''
arr = np.array([1, 2, 3, 4])
result = arr + 10
print(result)

# 1D and 2D Arrays
a = np.array([[1, 2, 3],
[4, 5, 6]])
b = np.array([10, 20, 30])
result = a + b
print(result)
'''b (1D array) is broadcasted across each row of a .
NumPy repeats b to match the 2D shape of a .'''

# Column Broadcasting
'''Shapes Before Broadcasting: 
Array A: (2, 3)
Array B: (3,)'''
# NumPy expands B → (1, 3) → (2, 3)
''' Final Operation:
A + B
Each row of A adds with B.
🧠 Rule:
Start from rightmost dimension.
Dimensions must be equal or one of them is 1.'''
a = np.array([[1, 2, 3],
[4, 5, 6]])
b = np.array([[10],
[20]])
result = a + b
print(result)
'''b is broadcasted column-wise.
NumPy expands b to match the shape of a .'''

[11 12 13 14]
[[11 22 33]
 [14 25 36]]
[[11 12 13]
 [24 25 26]]
